version: '3.8'

services:
  nestjs:
    build: .
    container_name: nestjs-app
    restart: always
    env_file: .env
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - nestjs
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
